/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js types in many setups. It is kept here so
// TypeScript works before the first local build.
